### ISSUE TITLE
ES_LOCAL_VERSION  env variables is empty

### ISSUE THREAD

**Issue by xiaohongred** [elastic/start-local#11]
es_version="$(get_latest_version)"

# Returns the latest Elasticsearch tag version
get_latest_version() {
  local tags="$(curl -s "https://api.github.com/repos/elastic/elasticsearch/tags")"
  local latest="$(echo "$tags" | grep -m 1 '"name"' | grep -Eo '[0-9.]+')"
  echo $latest
}

link "https://api.github.com/repos/elastic/elasticsearch/tags"  have rate limit,  i offen get empty ES_LOCAL_VERSION  env variable

**Comment by xiaohongred** [comment]
It may be because my company is using a network proxy.

**Comment by ezimuel** [comment]
@xiaohongred good point, I think other people can be in the same situation. I'm thinking to write the latest version in the script and update it when we have a new Elasticsearch release. In this way we don't need anymore to invoke the github API.

**Comment by ezimuel** [comment]
The PR https://github.com/elastic/start-local/pull/18 should fix this.

**Comment by ezimuel** [comment]
@xiaohongred fixed in 0.3.0. You can try now it should work since I removed the need to call github.
