### ISSUE TITLE
Issue with "grep -P" in some MacOS environments

### ISSUE THREAD

**Issue by ezimuel** [elastic/start-local#2]
There is an issue with the usage of `grep -P` command that is not available on MacOS 14.6.1. It seems this version uses an old version of grep 2.6.0-FreeBSD. This code is used in start-local.sh [here](https://github.com/elastic/start-local/blob/main/start-local.sh#L179).

**Comment by codefromthecrypt** [comment]
workaround is to `brew install grep` then `export  PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"` first
