### ISSUE TITLE
es-local-dev is unhealthy

### ISSUE THREAD

**Issue by Sid797** [elastic/start-local#20]
dependency failed to start: container es-local-dev is unhealthy
Error: docker compose up --wait command failed!
main: line 63: VERSION: unbound variable
An error log has been generated in error-start-local.log file.
If you need assistance, open an issue at https://github.com/elastic/start-local/issues

am i doing something wrong?

**Comment by Sid797** [comment]
so i was looking into the line 63 of start script which is causing the error and it is expecting version and distribution from os-release file i  think,but in my arch linux the os release file has format like this

NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux


so there is no version mentioned in that file.maybe this can help you

**Comment by ezimuel** [comment]
HI @Sid797 did you try to execute start-local using the command:
```bash
curl -fsSL https://elastic.co/start-local | sh
```
If so, can you share the error-start-local.log file? Thanks.

**Comment by Sid797** [comment]
yep,just used it again to see if i was using something else lol.This is the error-start-log file.Sorry,I didnt know what part you wanted so i pasted the entire thing.


Error: docker compose up --wait command failed!
Docker engine: Docker version 27.3.1, build ce1223035a
Docker compose: 2.30.3
Distribution: Arch Linux
-- Logs of service es-local-dev:
Created elasticsearch keystore in /usr/share/elasticsearch/config/elasticsearch.keystore
CompileCommand: dontinline java/lang/invoke/MethodHandle.setAsTypeCache bool dontinline = true
CompileCommand: dontinline java/lang/invoke/MethodHandle.asTypeUncached bool dontinline = true
{"@timestamp":"2024-11-14T18:25:28.133Z", "log.level": "INFO", "message":"Using native vector library; to disable start with -Dorg.elasticsearch.nativeaccess.enableVectorLibrary=false", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.nativeaccess.NativeAccess","elasticsearch.node.name":"fc1be577fdaf","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-11-14T18:25:28.223Z", "log.level": "INFO", "message":"Using [jdk] native provider and native methods for [Linux]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.nativeaccess.NativeAccess","elasticsearch.node.name":"fc1be577fdaf","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-11-14T18:25:28.610Z", "log.level": "INFO", "message":"Java vector incubator API enabled; uses preferredBitSize=256; FMA enabled", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.apache.lucene.internal.vectorization.PanamaVectorizationProvider","elasticsearch.node.name":"fc1be577fdaf","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-11-14T18:25:30.704Z", "log.level": "INFO", "message":"version[8.16.0], pid[216], build[docker/12ff76a92922609df4aba61a368e7adf65589749/2024-11-08T10:05:56.292914697Z], OS[Linux/6.11.6-arch1-1/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/23/23+37-2369]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"fc1be577fdaf","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-11-14T18:25:30.704Z", "log.level": "INFO", "message":"JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"fc1be577fdaf","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-11-14T18:25:30.705Z", "log.level": "INFO", "message":"JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=CLDR, --enable-native-access=org.elasticsearch.nativeaccess,org.apache.lucene.core, -Des.cgroups.hierarchy.override=/, -XX:ReplayDataFile=logs/replay_pid%p.log, -Des.distribution.type=docker, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-13466188973569789385, --add-modules=jdk.incubator.vector, -XX:CompileCommand=dontinline,java/lang/invoke/MethodHandle.setAsTypeCache, -XX:CompileCommand=dontinline,java/lang/invoke/MethodHandle.asTypeUncached, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,level,pid,tags:filecount=32,filesize=64m, -Xms128m, -Xmx2g, -XX:MaxDirectMemorySize=1073741824, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, --module-path=/usr/share/elasticsearch/lib, --add-modules=jdk.net, --add-modules=ALL-MODULE-PATH, -Djdk.module.main=org.elasticsearch.server]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"fc1be577fdaf","elasticsearch.cluster.name":"docker-cluster"}
{"@timestamp":"2024-11-14T18:25:30.705Z", "log.level": "INFO", "message":"Default Locale [en_US]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"fc1be577fdaf","elasticsearch.cluster.name":"docker-cluster"}
-- Logs of service kibana-local-dev:
-- Logs of service kibana_settings:

**Comment by amrohendawi** [comment]
```bash
curl -fsSL https://elastic.co/start-local | sh

  ______ _           _   _
 |  ____| |         | | (_)
 | |__  | | __ _ ___| |_ _  ___
 |  __| | |/ _` / __| __| |/ __|
 | |____| | (_| \__ \ |_| | (__
 |______|_|\__,_|___/\__|_|\___|
-------------------------------------------------
🚀 Run Elasticsearch and Kibana for local testing
-------------------------------------------------

ℹ️  Do not use this script in a production environment

It seems you have already a start-local installation in 'elastic-start-local'.
I cannot proceed unless you uninstall it, using the following command:
cd elastic-start-local && ./uninstall.sh
⌛️ Setting up Elasticsearch and Kibana v8.16.0...

- Generated random passwords
- Created the elastic-start-local folder containing the files:
  - .env, with settings
  - docker-compose.yml, for Docker services
  - start/stop/uninstall commands
- Running docker compose up --wait

[+] Running 4/4
 ✔ Network elastic-start-local_default  Created                                                                                                         0.0s
 ✘ Container es-local-dev               Error                                                                                                           2.6s
 ✔ Container kibana_settings            Created                                                                                                         0.0s
 ✔ Container kibana-local-dev           Created                                                                                                         0.0s
dependency failed to start: container es-local-dev exited (70)
Error: docker compose up --wait command failed!
An error log has been generated in error-start-local.log file.
If you need assistance, open an issue at https://github.com/elastic/start-local/issues
```

**Comment by ezimuel** [comment]
@Sid797 In the log that you reported there is no evidence of error. I'm wondering if you have enough RAM available. For running Elasticsearch and Kibana the requirement is about 4 GB. How much free memory do you have (`free -h`)?

**Comment by ezimuel** [comment]
@Sid797 out of curiosity, how much RAM do you have in total and how much is still free? I'm asking because maybe we can insert some check inside the start-local script. Thanks for your feedback!

**Comment by amrohendawi** [comment]
> [@Sid797](https://github.com/Sid797) and [@amrohendawi](https://github.com/amrohendawi) out of curiosity, how much RAM do you have in total and how much is still free? I'm asking because maybe we can insert some check inside the start-local script. Thanks for your feedback!

out of the 36GB RAM I have in my macbook pro with M3 chip docker can access 16 GB of memory

**Comment by Sid797** [comment]
ohh i am so sorry for the late reply @ezimuyel ,so my total ram is 4gb but ofcourse its usually around 2 thats free

did  `free-h` and got this

free -h
               total        used        free      shared  buff/cache   available
Mem:           3.7Gi       972Mi       1.7Gi       109Mi       1.4Gi       2.8Gi
Swap:          1.9Gi        41Mi       1.8Gi

so yea i guess when i get a better laptop I'll use elasticsearch :).

Thanks for the help and taking your time for this!!

**Comment by ezimuel** [comment]
@Sid797 thanks for sharing this information. With only 2 GB of free memory it's a challenge to run [Elasticsearch](https://github.com/elastic/elasticsearchkib) and [Kibana](https://github.com/elastic/kibana). We are thinking to add the possibility to run only Elasticsearch using start-local. I'll update you when we'll implement this so you can use Elasticsearch on your laptop.

**Comment by TathagataRoy1278** [comment]
Hello,

I have been trying to run elastisearch and kibana but running into the same problem.

For context, I was previously working on ubuntu 22 and it worked fine. However, I recently switched to EndeavourOS and am facing some problems(other than the obvious pain of switching to arch :)  )

```
  ______ _           _   _
 |  ____| |         | | (_)
 | |__  | | __ _ ___| |_ _  ___
 |  __| | |/ _` / __| __| |/ __|
 | |____| | (_| \__ \ |_| | (__
 |______|_|\__,_|___/\__|_|\___|
-------------------------------------------------
🚀 Run Elasticsearch and Kibana for local testing
-------------------------------------------------

ℹ️  Do not use this script in a production environment

⌛️ Setting up Elasticsearch and Kibana v8.17.0...

- Generated random passwords
- Created the elastic-start-local folder containing the files:
  - .env, with settings
  - docker-compose.yml, for Docker services
  - start/stop/uninstall commands
- Running docker compose up --wait

[+] Running 6/6
 ✔ Network elastic-start-local_default             Created                                           0.3s
 ✔ Volume "elastic-start-local_dev-kibana"         Crea...                                           0.0s
 ✔ Volume "elastic-start-local_dev-elasticsearch"  Created                                           0.0s
 ✘ Container es-local-dev                          Error                                             2.6s
 ✔ Container kibana_settings                       Created                                           0.1s
 ✔ Container kibana-local-dev                      Created                                           0.1s
dependency failed to start: container es-local-dev exited (74)
Error: docker compose up --wait command failed!
An error log has been generated in error-start-local.log file.
If you need assistance, open an issue at https://github.com/elastic/start-local/issues
```

the `error-start-local.log` file is 
```
Error: docker compose up --wait command failed!
Docker engine: Docker version 27.4.0, build bde2b89
Docker compose: 2.31.0
Distribution: EndeavourOS Version: TEST
-- Logs of service es-local-dev:
-- Logs of service kibana-local-dev:
-- Logs of service kibana_settings:
```

My free -h is

```
               total        used        free      shared  buff/cache   available
Mem:            14Gi       3,3Gi        11Gi       151Mi       911Mi        11Gi
Swap:             0B          0B          0B
```

previously most of the memory was in buff/cache, but I cleared everything just in case, but the problem still persists.

Any help would be highly appreciated.

Thank you!

**Comment by ezimuel** [comment]
@Sid797 good news, I just released [0.8.0](https://github.com/elastic/start-local/releases/tag/0.8.0) version that includes the possibility to install only Elasticsearch with the `-esonly` option You can use the following command:
```bash
curl -fsSL https://elastic.co/start-local | sh -s -- -esonly
```
Let me know if now you can install Elasticsearch. Of course, you will not have Kibana that means you need to interact using REST API, you can have a look at the documentation, [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/quickstart.html). For a quick test, you can use the cURL commands, just copy & paste the examples using the shell (`Copy as curl` in the box, see image).

![Image](https://github.com/user-attachments/assets/9456aac5-ab0f-474b-821a-fd83574c07c5)

After these tests, you can start using the [Elasticsearch Clients](https://www.elastic.co/guide/en/elasticsearch/client/index.html) to develop applications using Elasticsearch with your favorite language.

**Comment by Sid797** [comment]
@ezimuel MAN GITHUB IS FILLED WITH THE MOST AMAZING PEOPLE!
It totally works,I was playing with it and will build something small with it really  soon and share it with you :)

Thank you so much man you are absolutely incredible ❤️❤️❤️❤️❤️❤️❤️

**Comment by Sid797** [comment]
And also if you want me to work on this repo or want any kind of help I would be more than happy to do it❤️❤️❤️

**Comment by ezimuel** [comment]
Thanks @Sid797, I'm happy that the solution worked. Thanks also for the proposal to contribute to the project. One way you can help is by sharing the project with anyone interested in Elasticsearch and the use cases or projects you experiment with.
