### ISSUE TITLE
"Invalid interpolation format for 'command' option in service 'kibana_settings'" after running `start-local.sh`

### ISSUE THREAD

**Issue by cioannid** [elastic/start-local#23]
I just run the `start-local.sh` and I received the following error:
```
% curl -fsSL https://elastic.co/start-local | sh

  ______ _           _   _      
 |  ____| |         | | (_)     
 | |__  | | __ _ ___| |_ _  ___ 
 |  __| | |/ _` / __| __| |/ __|
 | |____| | (_| \__ \ |_| | (__ 
 |______|_|\__,_|___/\__|_|\___|
-------------------------------------------------
🚀 Run Elasticsearch and Kibana for local testing
-------------------------------------------------

ℹ️  Do not use this script in a production environment

⌛️ Setting up Elasticsearch and Kibana v8.16.0...

- Generated random passwords
- Created the elastic-start-local folder containing the files:
  - .env, with settings
  - docker-compose.yml, for Docker services
  - start/stop/uninstall commands
- Running docker-compose up -d

ERROR: Invalid interpolation format for "command" option in service "kibana_settings": "bash -c '
  echo "Setup the kibana_system password";
  start_time=$(date +%s);
  timeout=60;
  until curl -s -u "elastic:${ES_LOCAL_PASSWORD}" -X POST http://elasticsearch:${ES_LOCAL_PORT}/_security/user/kibana_system/_password -d "{\"password\":\"'${KIBANA_LOCAL_PASSWORD}'\"}" -H "Content-Type: application/json" | grep -q "^{}"; do if [ $(($(date +%s) - $$start_time)) -ge $$timeout ]; then echo "Error: Elasticsearch timeout"; exit 1; fi; sleep 2; done;
'
"
Error: docker-compose up -d command failed!
An error log has been generated in error-start-local.log file.
If you need assistance, open an issue at https://github.com/elastic/start-local/issues
% cat error-start-local.log 
Error: docker-compose up -d command failed!
Docker engine: Docker version 20.10.24+dfsg1, build 297e128
Docker compose: 1.29.2
Distribution: Debian GNU/Linux Version: 12 (bookworm)
-- Logs of service es-local-dev:
-- Logs of service kibana-local-dev:
-- Logs of service kibana_settings:
```
The essence of this error is:
```
Invalid interpolation format for "command" option in service "kibana_settings"
```
I noticed that [the mentioned command was changed yesterday](https://github.com/elastic/start-local/commit/fec060f21072c1079e4d0ca0aae598387a0f2c14#diff-0f6d946a7d25b999dae17f0b4d8e674e55efefe7a9eb9556ad6182c84e67011dR552). Could you take a look? Thanks.

**Comment by ezimuel** [comment]
@cioannid thanks for reporting this. Can you give me the following information about your environment?
-  OS type and version
- grep version (`grep --version`)
- Docker engine version ('docker --version`)
- Docker compose version (`docker compose version`)
Thanks!

**Comment by cioannid** [comment]
Hello @ezimuel!

Thanks for the prompt reply.

Can you give me the following information about your environment?
> 
> * OS type and version
> * grep version (`grep --version`)
> * Docker engine version ('docker --version`)
> * Docker compose version (`docker compose version`)
>   Thanks!

They are listed at the bottom of the error log in my initial message.

However, I just upgraded both docker engine and docker compose to the latest versions and the problem got solved. Apologies for the early GitHub issue.

Thanks!

**Comment by ezimuel** [comment]
Sorry, I miss the information. No problem for the issue. Let me know if you need more help.
