### ISSUE TITLE
Broken uninstall script?

### ISSUE THREAD

**Issue by glebbash** [elastic/start-local#24]
I think there is a missing end quote character here: https://github.com/elastic/start-local/blob/7ce219aa89c37b5c5a806e225fb7a92b1bbd1b98/start-local.sh#L487C4-L487C40

**Comment by ezimuel** [comment]
Thanks @glebbash . This condition is not tested in the automated tests. I'll fix it.

**Comment by ezimuel** [comment]
Fixed in version [0.4.1](https://github.com/elastic/start-local/releases/tag/0.4.1)
