### ISSUE TITLE
Not able to login on local setup with the credentials given in .env file.

### ISSUE THREAD

**Issue by ibrahim-string** [elastic/start-local#9]
I am not able to login with the credentials given in the .env file. 
Here is the screenshot: 

![Image](https://github.com/user-attachments/assets/6352a0d0-6ba9-41b9-bf42-6fd25de4b853)

**Comment by ezimuel** [comment]
The username is `elastic` and the URL for managing Elasticsearch is `http://localhost:5601`. The password is the one generated by `start-local` and stored in the `elastic-start-local/.env` file. The URL `http://localhost:9200` is for the Elasticsearch server, but you need a client, like [curl](https://curl.se/) or a custom program using our [SDK](https://www.elastic.co/guide/en/elasticsearch/client/index.html) to interact with Elasticsearch using [REST API](https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html). For more information you can read the [Elasticsearch guide](https://www.elastic.co/guide/en/elasticsearch/reference/8.15/index.html).

**Comment by ibrahim-string** [comment]
Hi @ezimuel Thank you, I figured it out.

**Comment by ezimuel** [comment]
@ibrahim-string when you execute the start-local script using the command:
```bash
curl -fsSL https://elastic.co/start-local | sh
```
the output contains the `elastic` username information.

![Image](https://github.com/user-attachments/assets/d860f41e-833c-44ad-a166-395aa34b3bd1)


Also in the [README](https://github.com/elastic/start-local?tab=readme-ov-file#-endpoints) is mentioned the `elastic` user. Maybe there are other doc pages that we did not update, let me know, thanks!
